# -*- coding: utf-8 -*-
"""CS-497-Team-Phrygian.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HqnpWgofEE4GRry4obFq9_cu9qGFD9K3
"""

# https://www.kaggle.com/washingtonpost/police-shootings

print('hello')